name: ARMEmulator
options:
  bundleIdPrefix: com.lookbusy1344
  deploymentTarget:
    macOS: "13.0"
  developmentLanguage: en
  xcodeVersion: "15.0"

settings:
  base:
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    MACOSX_DEPLOYMENT_TARGET: "13.0"
    SWIFT_VERSION: "5.9"
    ENABLE_HARDENED_RUNTIME: YES
    COMBINE_HIDPI_IMAGES: YES

targets:
  ARMEmulator:
    type: application
    platform: macOS
    deploymentTarget: "13.0"
    sources:
      - path: ARMEmulator
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.lookbusy1344.ARMEmulator
        PRODUCT_NAME: ARMEmulator
        INFOPLIST_FILE: ARMEmulator/Resources/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        GENERATE_INFOPLIST_FILE: NO
        ENABLE_PREVIEWS: YES
    dependencies:
      - sdk: SwiftUI.framework
      - sdk: Combine.framework
      - sdk: Foundation.framework
      - sdk: AppKit.framework
    postBuildScripts:
      - name: Copy Backend Binary
        script: |
          BACKEND_SOURCE="${PROJECT_DIR}/../arm-emulator"
          RESOURCES_DIR="${BUILT_PRODUCTS_DIR}/${PRODUCT_NAME}.app/Contents/Resources"
          BACKEND_DEST="${RESOURCES_DIR}/arm-emulator"

          if [ -f "$BACKEND_SOURCE" ]; then
            echo "Copying backend binary to app bundle..."
            mkdir -p "$RESOURCES_DIR"
            cp "$BACKEND_SOURCE" "$BACKEND_DEST"
            chmod +x "$BACKEND_DEST"
            echo "Backend binary copied successfully to $BACKEND_DEST"
          else
            echo "Warning: Backend binary not found at $BACKEND_SOURCE"
            echo "The backend must be built separately with version info:"
            echo "  cd ${PROJECT_DIR}/.."
            echo "  VERSION=\"1.0.0\""
            echo "  COMMIT=\$(git log -1 --format=%H)"
            echo "  DATE=\$(date -u +\"%Y-%m-%d %H:%M:%S UTC\")"
            echo "  go build -ldflags \"-X 'main.Version=\$VERSION' -X 'main.Commit=\$COMMIT' -X 'main.Date=\$DATE'\" -o arm-emulator"
          fi
    scheme:
      testTargets:
        - ARMEmulatorTests
      gatherCoverageData: true

  ARMEmulatorTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - ARMEmulatorTests
    dependencies:
      - target: ARMEmulator
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.lookbusy1344.ARMEmulatorTests
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES
        GENERATE_INFOPLIST_FILE: YES

schemes:
  ARMEmulator:
    build:
      targets:
        ARMEmulator: all
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      targets:
        - ARMEmulatorTests
    archive:
      config: Release
