// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddBreakpoint(arg1) {
  return window['go']['main']['App']['AddBreakpoint'](arg1);
}

export function Continue() {
  return window['go']['main']['App']['Continue']();
}

export function GetBreakpoints() {
  return window['go']['main']['App']['GetBreakpoints']();
}

export function GetExecutionState() {
  return window['go']['main']['App']['GetExecutionState']();
}

export function GetMemory(arg1, arg2) {
  return window['go']['main']['App']['GetMemory'](arg1, arg2);
}

export function GetRegisters() {
  return window['go']['main']['App']['GetRegisters']();
}

export function GetSourceLine(arg1) {
  return window['go']['main']['App']['GetSourceLine'](arg1);
}

export function GetSymbols() {
  return window['go']['main']['App']['GetSymbols']();
}

export function IsRunning() {
  return window['go']['main']['App']['IsRunning']();
}

export function LoadProgramFromSource(arg1, arg2, arg3) {
  return window['go']['main']['App']['LoadProgramFromSource'](arg1, arg2, arg3);
}

export function Pause() {
  return window['go']['main']['App']['Pause']();
}

export function RemoveBreakpoint(arg1) {
  return window['go']['main']['App']['RemoveBreakpoint'](arg1);
}

export function Reset() {
  return window['go']['main']['App']['Reset']();
}

export function Step() {
  return window['go']['main']['App']['Step']();
}
