// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';

export function AddBreakpoint(arg1:number):Promise<void>;

export function AddWatchpoint(arg1:number,arg2:string):Promise<void>;

export function ClearAllBreakpoints():Promise<void>;

export function Continue():Promise<void>;

export function EvaluateExpression(arg1:string):Promise<number>;

export function ExecuteCommand(arg1:string):Promise<string>;

export function GetBreakpoints():Promise<Array<service.BreakpointInfo>>;

export function GetCurrentFilename():Promise<string>;

export function GetDisassembly(arg1:number,arg2:number):Promise<Array<service.DisassemblyLine>>;

export function GetExecutionState():Promise<string>;

export function GetLastMemoryWrite():Promise<service.MemoryWriteInfo>;

export function GetMemory(arg1:number,arg2:number):Promise<Array<number>>;

export function GetOutput():Promise<string>;

export function GetRegisters():Promise<service.RegisterState>;

export function GetSourceLine(arg1:number):Promise<string>;

export function GetSourceMap():Promise<Array<service.SourceMapEntry>>;

export function GetStack(arg1:number,arg2:number):Promise<Array<service.StackEntry>>;

export function GetSymbolForAddress(arg1:number):Promise<string>;

export function GetSymbols():Promise<Record<string, number>>;

export function GetSymbolsForAddresses(arg1:Array<number>):Promise<Record<number, string>>;

export function GetWatchpoints():Promise<Array<service.WatchpointInfo>>;

export function GetWindowTitle():Promise<string>;

export function IsRunning():Promise<boolean>;

export function LoadProgramFromFile():Promise<void>;

export function LoadProgramFromSource(arg1:string,arg2:string,arg3:number):Promise<void>;

export function Pause():Promise<void>;

export function RemoveBreakpoint(arg1:number):Promise<void>;

export function RemoveWatchpoint(arg1:number):Promise<void>;

export function Reset():Promise<void>;

export function Restart():Promise<void>;

export function SendInput(arg1:string):Promise<void>;

export function Step():Promise<void>;

export function StepOut():Promise<void>;

export function StepOver():Promise<void>;

export function ToggleBreakpoint(arg1:number):Promise<void>;
