// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddBreakpoint(arg1) {
  return window['go']['main']['App']['AddBreakpoint'](arg1);
}

export function AddWatchpoint(arg1, arg2) {
  return window['go']['main']['App']['AddWatchpoint'](arg1, arg2);
}

export function ClearAllBreakpoints() {
  return window['go']['main']['App']['ClearAllBreakpoints']();
}

export function Continue() {
  return window['go']['main']['App']['Continue']();
}

export function EvaluateExpression(arg1) {
  return window['go']['main']['App']['EvaluateExpression'](arg1);
}

export function ExecuteCommand(arg1) {
  return window['go']['main']['App']['ExecuteCommand'](arg1);
}

export function GetBreakpoints() {
  return window['go']['main']['App']['GetBreakpoints']();
}

export function GetCurrentFilename() {
  return window['go']['main']['App']['GetCurrentFilename']();
}

export function GetDisassembly(arg1, arg2) {
  return window['go']['main']['App']['GetDisassembly'](arg1, arg2);
}

export function GetExecutionState() {
  return window['go']['main']['App']['GetExecutionState']();
}

export function GetLastMemoryWrite() {
  return window['go']['main']['App']['GetLastMemoryWrite']();
}

export function GetMemory(arg1, arg2) {
  return window['go']['main']['App']['GetMemory'](arg1, arg2);
}

export function GetOutput() {
  return window['go']['main']['App']['GetOutput']();
}

export function GetRegisters() {
  return window['go']['main']['App']['GetRegisters']();
}

export function GetSourceLine(arg1) {
  return window['go']['main']['App']['GetSourceLine'](arg1);
}

export function GetSourceMap() {
  return window['go']['main']['App']['GetSourceMap']();
}

export function GetStack(arg1, arg2) {
  return window['go']['main']['App']['GetStack'](arg1, arg2);
}

export function GetSymbolForAddress(arg1) {
  return window['go']['main']['App']['GetSymbolForAddress'](arg1);
}

export function GetSymbols() {
  return window['go']['main']['App']['GetSymbols']();
}

export function GetSymbolsForAddresses(arg1) {
  return window['go']['main']['App']['GetSymbolsForAddresses'](arg1);
}

export function GetWatchpoints() {
  return window['go']['main']['App']['GetWatchpoints']();
}

export function GetWindowTitle() {
  return window['go']['main']['App']['GetWindowTitle']();
}

export function IsRunning() {
  return window['go']['main']['App']['IsRunning']();
}

export function LoadProgramFromFile() {
  return window['go']['main']['App']['LoadProgramFromFile']();
}

export function LoadProgramFromSource(arg1, arg2, arg3) {
  return window['go']['main']['App']['LoadProgramFromSource'](arg1, arg2, arg3);
}

export function Pause() {
  return window['go']['main']['App']['Pause']();
}

export function RemoveBreakpoint(arg1) {
  return window['go']['main']['App']['RemoveBreakpoint'](arg1);
}

export function RemoveWatchpoint(arg1) {
  return window['go']['main']['App']['RemoveWatchpoint'](arg1);
}

export function Reset() {
  return window['go']['main']['App']['Reset']();
}

export function Restart() {
  return window['go']['main']['App']['Restart']();
}

export function Step() {
  return window['go']['main']['App']['Step']();
}

export function StepOut() {
  return window['go']['main']['App']['StepOut']();
}

export function StepOver() {
  return window['go']['main']['App']['StepOver']();
}

export function ToggleBreakpoint(arg1) {
  return window['go']['main']['App']['ToggleBreakpoint'](arg1);
}
