// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';

export function AddBreakpoint(arg1:number):Promise<void>;

export function Continue():Promise<void>;

export function GetBreakpoints():Promise<Array<service.BreakpointInfo>>;

export function GetExecutionState():Promise<string>;

export function GetMemory(arg1:number,arg2:number):Promise<Array<number>>;

export function GetRegisters():Promise<service.RegisterState>;

export function GetSourceLine(arg1:number):Promise<string>;

export function GetSymbols():Promise<Record<string, number>>;

export function IsRunning():Promise<boolean>;

export function LoadProgramFromSource(arg1:string,arg2:string,arg3:number):Promise<void>;

export function Pause():Promise<void>;

export function RemoveBreakpoint(arg1:number):Promise<void>;

export function Reset():Promise<void>;

export function Step():Promise<void>;
