<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <!-- Testing Framework -->
    <PackageReference Include="xunit.v3" Version="4.*" />

    <!-- Mocking & Assertions -->
    <PackageReference Include="NSubstitute" Version="6.*" />
    <PackageReference Include="AwesomeAssertions" Version="9.*" />

    <!-- Avalonia Headless Testing -->
    <PackageReference Include="Avalonia.Headless.XUnit" Version="12.1.*" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ARMEmulator\ARMEmulator.csproj" />
  </ItemGroup>

</Project>